// <auto-generated />
using System;
using AutomatedFinances.Core.MigrationInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomatedFinances.Core.Migrations
{
    [DbContext(typeof(IridiumDbMigrationContext))]
    [Migration("20221008103735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutomatedFinances.Core.Entities.GenericTransaction", b =>
                {
                    b.Property<Guid>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccuredAtDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RecordedAtDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SavedAtDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SavedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TrackingId");

                    b.ToTable("GenericTransaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
